name: likui24
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# zuul:
#   routes:
#     api-uac:
#       path: /api-uac/**
#       service-id: plaza-provider-uac
#     api-omc:
#       path: /api-omc/**
#       service-id: plaza-provider-omc
#     api-psc:
#       path: /api-psc/**
#       service-id: plaza-provider-psc
#       sensitive-headers:
#     ignored-patterns:
#       - /**/product/listForOrder
