name: zhangsan
age: 21
version: dev
spring:
  datasource:
    url: '{cipher}AQCP3I3C1ac45Mle9313xhm31PWrRtHps91lpznuIBiPVsp6rQH5o+Qf3Z3Hn/ny+vEbfdTJTp1YIB8QCcchzesSW7q/X3DSRBCWXvGmFxoj4VNxCN1qQzAp3UJaA7W2VM/N4UWJ6t2TJYxpi1nOWOOddb1k1DS7UmqPKa5tt89wgR7fKsArlvKhk9a5ZRDZr9PoKnTxAc0vMsUQwlRIUNGRE9luX43Yyqq6Ijh5fNHnBPQv07iUiTAOnK61Zi1rpkgmtTHjEsf/TIP3XtqBkzBjDCiQEMqYbM6t8OySzyK50Ln3dUJvHzgQ85sLhcVpvNWEqOA+x5SyKlUkV3qHV8JQBeDSYxlOt1k/6rMaPPCyDkdlz8DzjagBoRcBw4SuvOI7FHUInT6ayLWu2heoOje7LfkgSZHtyee1CugrtK5yXg=='
    username: '{cipher}AQCFSy4ZEB3qhpovX1XY9M/bePl5FCje6rxfq6sPvn3IU4Ij6VYdiJklobwvsu9LIp1Cpi2GskNHKUkfjtFR/85Q3XYvnpVSEAku3V2x3TpeIrnX0xpYsqg+7g/LAtuteF5PWuBtx/ZU+0xgyhByc6tm1lOkvZmOg8YFH4IMCmsNvcfyFg9s77nr3LCj5l8+vq19o3OMHemPC/ADda1mHOGacyWMbYYvopoCRej4ayiTXK7XQdqYftWIUTM1xxZlm1gm6cy5kcO93g1IlgdoqAgvmSyxw4pOZoASBOmUHYoDC/+uo7zkZ9S7Wz+hqNdRMzt0onDOFmfBCNJJBvJdDGY1l+BwvYLv8/9E10JkU8GU1qTykUFhqGsU14E6W4zSjZs='
    password: '{cipher}AQCFSy4ZEB3qhpovX1XY9M/bePl5FCje6rxfq6sPvn3IU4Ij6VYdiJklobwvsu9LIp1Cpi2GskNHKUkfjtFR/85Q3XYvnpVSEAku3V2x3TpeIrnX0xpYsqg+7g/LAtuteF5PWuBtx/ZU+0xgyhByc6tm1lOkvZmOg8YFH4IMCmsNvcfyFg9s77nr3LCj5l8+vq19o3OMHemPC/ADda1mHOGacyWMbYYvopoCRej4ayiTXK7XQdqYftWIUTM1xxZlm1gm6cy5kcO93g1IlgdoqAgvmSyxw4pOZoASBOmUHYoDC/+uo7zkZ9S7Wz+hqNdRMzt0onDOFmfBCNJJBvJdDGY1l+BwvYLv8/9E10JkU8GU1qTykUFhqGsU14E6W4zSjZs='
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    port: 6379
