name: likui25
spring:
  redis:
    host: 127.0.0.1
    port: 6379
zuul:
  sensitive-headers: Authorization  #全局都可以传递cookie
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 30000
  routes:
    api-oauth:
      path: /uaa/**
      service-id: plaza-oauth
    api-uac:
      path: /api-uac/**
      service-id: plaza-provider-uac
    api-omc:
      path: /api-omc/**
      service-id: plaza-provider-omc
    api-psc:
      path: /api-psc/**
      service-id: plaza-provider-psc
      sensitive-headers:  #单个路由可以传递cookie
#     ignored-patterns:
#       - /**/product/listForOrder
