name: psc
spring:
  datasource:
    url: '{cipher}AQCFKZUSc7l1m+gEeUL3+oAGCZyBHmwEwN2dy/8l5pF8+Dm3FtSsiNEhVD9K6opmio7L8C/N2SWH2VKTx0n3WbELPrBZdtuHdGsb9L/5zHmzcfnptSnqNwuV6xCAtlVgFeZ/rSGWey/RmauseelAIkgXgd1BESYE3k5N2CVl5dyAB0OzOzoxUSv1elVh1Krmi0/YMY2TWcCwHDhTLtJt68hCHOLry+LSSX0cTyJBF9BBgaMtWsd3gR4klpWXeVk3sBlXGTy2GCbJl3FvhYFEcddsUXHksWT3dBQwaq0rCsM437zg7Q6cKJxa04IwSylRpOt/jMqKuqgAQ/3/T5SQKhRBgfR0X/PXFyiGbSLKg1j917IhyGprJuMJQsy2NobHHKZFnw5NGQIm48gY1HYBCmUJ17yrZP7m8TQYWc4glaimiw=='
    username: '{cipher}AQB/U/LDex270BR1dW4kdOL8QIfKDQsqVjklHAT/S4jW11cY+An1XQA1nLpSCxq+HSdW4KcVEhiar4tqCtlwWT0towwxuqdgX3uJkAQfeXT+3F/Nd1hxVrQFOvFbY1FM4lH2nt45FKBq2tDRJFOaqQUqeZVyg89jxI2EJhsXbKfT6h01BEaJpTS5KpQe4AhTwEtVRNvmGwbcXAdWgtu3/5cNIsutmK6GYSAM1qSFe1qR6UDxYTpEiB6G60Q25+fPl9XMc0Cesl5MMHamog+e9c196pdKlbl6VJ8EzFyAS2j6qUzCDK1eNY9HzTqj5bMrQGHMoHNdWcXNZrZN7N80HBJf4iLzY3zXych7q+piq+lZ0fTfeGzGEAAUI5/UPTF1HSU='
    password: '{cipher}AQB/U/LDex270BR1dW4kdOL8QIfKDQsqVjklHAT/S4jW11cY+An1XQA1nLpSCxq+HSdW4KcVEhiar4tqCtlwWT0towwxuqdgX3uJkAQfeXT+3F/Nd1hxVrQFOvFbY1FM4lH2nt45FKBq2tDRJFOaqQUqeZVyg89jxI2EJhsXbKfT6h01BEaJpTS5KpQe4AhTwEtVRNvmGwbcXAdWgtu3/5cNIsutmK6GYSAM1qSFe1qR6UDxYTpEiB6G60Q25+fPl9XMc0Cesl5MMHamog+e9c196pdKlbl6VJ8EzFyAS2j6qUzCDK1eNY9HzTqj5bMrQGHMoHNdWcXNZrZN7N80HBJf4iLzY3zXych7q+piq+lZ0fTfeGzGEAAUI5/UPTF1HSU='
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 
